### Working with pandas library

In [2]:
from google.colab import drive

ModuleNotFoundError: No module named 'google.colab'

In [2]:
drive.mount('/content/Drive')

Mounted at /content/Drive

In [3]:
import pandas as pd

In [18]:
data = pd.read_excel('/content/Drive/MyDrive/progMaria/global_progMaria.xlsx')

In [19]:
data.head(10)

,Unnamed: 0,IDADE,FAIXA IDADE,GENERO,COR/RACA/ETNIA,PCD,EXPERIENCIA_PROFISSIONAL_PREJUDICADA,PREJUDICA?,ASPECTOS_PREJUDICADOS,VIVE_NO_BRASIL,...,SETOR,NUMERO DE FUNCIONARIOS,GESTOR?,NIVEL,NOVO NÍVEL,CARGO COMO GESTOR,CARGO ATUAL,FAIXA SALARIAL,QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?,QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,39.0,35-39,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Setor Público,Acima de 3.000,False,Júnior,Júnior,NaN,DBA/Administrador de Banco de Dados,de R$ 8.001/mês a R$ 12.000/mês,de 1 a 2 anos,de 7 a 10 anos
1,zzls2oftfn9law393oezzls2ofhvfpzd,32.0,30-34,Masculino,Parda,Não,"Sim, acredito que a minha a experiência profis...",TRUE,Aprovação em processos seletivos/entrevistas,True,...,Outra Opção,Acima de 3.000,True,NaN,Gestora,Supervisor/Coordenador,NaN,de R$ 4.001/mês a R$ 6.000/mês,de 3 a 4 anos,Menos de 1 ano
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,53.0,50-54,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Finanças ou Bancos,Acima de 3.000,False,Pleno,Pleno,NaN,Desenvolvedor/ Engenheiro de Software/ Analist...,de R$ 12.001/mês a R$ 16.000/mês,de 3 a 4 anos,Mais de 10 anos
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,27.0,25-29,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Setor Automotivo,Acima de 3.000,False,Sênior,Sênior,NaN,Cientista de Dados/Data Scientist,de R$ 12.001/mês a R$ 16.000/mês,de 4 a 6 anos,Não tive experiência na área de TI/Engenharia ...
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,46.0,45-49,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Setor Público,de 101 a 500,False,Pleno,Pleno,NaN,Desenvolvedor/ Engenheiro de Software/ Analist...,de R$ 6.001/mês a R$ 8.000/mês,Não tenho experiência na área de dados,Mais de 10 anos
5,zz0nlhbd8oxyiyxzz0nlh7g4xkiaza5v,32.0,30-34,Feminino,Parda,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Educação,Acima de 3.000,False,Pleno,Pleno,NaN,Professor,de R$ 2.001/mês a R$ 3.000/mês,Não tenho experiência na área de dados,Não tive experiência na área de TI/Engenharia ...
6,zytlxsdgalh22cgrijvzytlxa49i8yzx,21.0,17-21,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Finanças ou Bancos,Acima de 3.000,False,Júnior,Júnior,NaN,Analista de BI/BI Analyst,de R$ 4.001/mês a R$ 6.000/mês,de 1 a 2 anos,Menos de 1 ano
7,zyc0twzno2sm5or5ovoxzyc0twz0300d,31.0,30-34,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Tecnologia/Fábrica de Software,de 6 a 10,False,Júnior,Júnior,NaN,Desenvolvedor/ Engenheiro de Software/ Analist...,de R$ 2.001/mês a R$ 3.000/mês,Menos de 1 ano,Menos de 1 ano
8,zy4o5dk6iuxpdwgzy4o58xvd6ykwohrj,33.0,30-34,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Tecnologia/Fábrica de Software,Acima de 3.000,False,Sênior,Sênior,NaN,Analista de BI/BI Analyst,de R$ 6.001/mês a R$ 8.000/mês,Menos de 1 ano,Não tive experiência na área de TI/Engenharia ...
9,zxc3d314cn1c2ovmzxc34ha7nkw1na3j,NaN,55+,Feminino,Parda,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Educação,Acima de 3.000,False,Pleno,Pleno,NaN,Professor,de R$ 8.001/mês a R$ 12.000/mês,Mais de 10 anos,Não tive experiência na área de TI/Engenharia ...

In [20]:
# to see the final rows

data.tail()

,Unnamed: 0,IDADE,FAIXA IDADE,GENERO,COR/RACA/ETNIA,PCD,EXPERIENCIA_PROFISSIONAL_PREJUDICADA,PREJUDICA?,ASPECTOS_PREJUDICADOS,VIVE_NO_BRASIL,...,SETOR,NUMERO DE FUNCIONARIOS,GESTOR?,NIVEL,NOVO NÍVEL,CARGO COMO GESTOR,CARGO ATUAL,FAIXA SALARIAL,QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?,QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?
4266,01jnrn9f6va0menfhk2ztm01jnrn96bp,26.0,25-29,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Tecnologia/Fábrica de Software,Acima de 3.000,False,Pleno,Pleno,NaN,Analista de Dados/Data Analyst,de R$ 4.001/mês a R$ 6.000/mês,de 3 a 4 anos,de 7 a 10 anos
4267,01dyfxam4u4bi29fem01dyfxaq9akvqp,30.0,30-34,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,FALSO,NaN,True,...,Área de Consultoria,de 51 a 100,False,Pleno,Pleno,NaN,Engenheiro de Dados/Arquiteto de Dados/Data En...,de R$ 3.001/mês a R$ 4.000/mês,de 1 a 2 anos,Não tive experiência na área de TI/Engenharia ...
4268,00zw9ks9d40z4u00zz3d20iix65qpli3,29.0,25-29,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Setor Imobiliário/ Construção Civil,de 101 a 500,True,NaN,Gestora,Gerente/Head,NaN,de R$ 16.001/mês a R$ 20.000/mês,de 4 a 6 anos,Não tive experiência na área de TI/Engenharia ...
4269,00xu7yujd7s57emj00xu7y0c3njix3de,NaN,17-21,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Indústria,de 1.001 a 3.000,False,Júnior,Júnior,NaN,Outra Opção,Menos de R$ 1.000/mês,Menos de 1 ano,Não tive experiência na área de TI/Engenharia ...
4270,00lb35llmdsidpa00lb35qcdysnzvhv7,24.0,22-24,Masculino,Branca,Não,NaN,FALSO,NaN,True,...,Agronegócios,de 501 a 1.000,False,Júnior,Júnior,NaN,Analista de Dados/Data Analyst,de R$ 3.001/mês a R$ 4.000/mês,de 1 a 2 anos,Não tive experiência na área de TI/Engenharia ...

NameError: name 'data' is not defined

In [21]:
# to see how long is the table
data.shape

(4271, 29)

In [22]:
# other options to discovery how many rows
len(data)

4271

In [23]:
# to discovery the name of all columns
data.columns

Index(['Unnamed: 0', 'IDADE', 'FAIXA IDADE', 'GENERO', 'COR/RACA/ETNIA', 'PCD',
       'EXPERIENCIA_PROFISSIONAL_PREJUDICADA', 'PREJUDICA?',
       'ASPECTOS_PREJUDICADOS', 'VIVE_NO_BRASIL', 'ESTADO ONDE MORA',
       'UF ONDE MORA', 'REGIAO ONDE MORA', 'MUDOU DE ESTADO?',
       'REGIAO DE ORIGEM', 'NIVEL DE ENSINO', 'ÁREA DE FORMAÇÃO',
       'COMPUTAÇÃO?', 'QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?', 'SETOR',
       'NUMERO DE FUNCIONARIOS', 'GESTOR?', 'NIVEL', 'NOVO NÍVEL',
       'CARGO COMO GESTOR', 'CARGO ATUAL', 'FAIXA SALARIAL',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?',
       'QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?'],
      dtype='object')

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271 entries, 0 to 4270
Data columns (total 29 columns):
 #   Column                                                                                                                     Non-Null Count  Dtype
---  ------                                                                                                                     --------------  -----
 0   Unnamed: 0                                                                                                                 4271 non-null   object
 1   IDADE                                                                                                                      4197 non-null   float64
 2   FAIXA IDADE                                                                                                                4271 non-null   object
 3   GENERO                                                                                                                     4262 non-null   object
 4   COR/RACA/ETNIA                                                                                                             4271 non-null   object
 5   PCD                                                                                                                        4271 non-null   object
 6   EXPERIENCIA_PROFISSIONAL_PREJUDICADA                                                                                       2190 non-null   object
 7   PREJUDICA?                                                                                                                 4271 non-null   object
 8   ASPECTOS_PREJUDICADOS                                                                                                      837 non-null    object
 9   VIVE_NO_BRASIL                                                                                                             4271 non-null   bool
 10  ESTADO ONDE MORA                                                                                                           4156 non-null   object
 11  UF ONDE MORA                                                                                                               4156 non-null   object
 12  REGIAO ONDE MORA                                                                                                           4171 non-null   object
 13  MUDOU DE ESTADO?                                                                                                           4171 non-null   object
 14  REGIAO DE ORIGEM                                                                                                           772 non-null    object
 15  NIVEL DE ENSINO                                                                                                            4271 non-null   object
 16  ÁREA DE FORMAÇÃO                                                                                                           4149 non-null   object
 17  COMPUTAÇÃO?                                                                                                                4271 non-null   bool
 18  QUAL SUA SITUAÇÃO ATUAL DE TRABALHO?                                                                                       4271 non-null   object
 19  SETOR                                                                                                                      3694 non-null   object
 20  NUMERO DE FUNCIONARIOS                                                                                                     3694 non-null   object
 21  GESTOR?                                                                                                                    3694 non-null   object
 22  NIVEL                                                                                                                      2981 non-null   object
 23  NOVO NÍVEL                                                                                                                 3694 non-null   object
 24  CARGO COMO GESTOR                                                                                                          713 non-null    object
 25  CARGO ATUAL                                                                                                                2981 non-null   object
 26  FAIXA SALARIAL                                                                                                             3694 non-null   object
 27  QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE DADOS VOCÊ TEM?                                                                     3694 non-null   object
 28  QUANTO TEMPO DE EXPERIÊNCIA NA ÁREA DE TI/ENGENHARIA DE SOFTWARE VOCÊ TEVE ANTES DE COMEÇAR A TRABALHAR NA ÁREA DE DADOS?  3694 non-null   object
dtypes: bool(2), float64(1), object(26)
memory usage: 909.4+ KB

In [30]:
data.describe()

             IDADE
count  4197.000000
mean     31.169168
std       6.902803
min      18.000000
25%      26.000000
50%      30.000000
75%      35.000000
max      54.000000